Node lesson 1
dandgerson/anderson-dmitry-otus pull request #4
Opened 2018-11-26 15:56 UTC by dandgerson

not working.
stack with serial requestType
not sure that all of other code is valid. 
please help with it.

2018-11-26 19:56 UTC, korzio requested changes

2018-11-26 19:56 UTC, korzio commented on node/lesson1/server.js
> +      console.log('response starting... ' + responseCount++);
Повторяющийся код с `:30`

2018-11-26 19:56 UTC, korzio commented on node/lesson1/server.js
> +new request.requester(1000, 'parallel').make().send();
Предполагалось, что `request` будет вызываться из командной строки - надо будет уточнить это в дз. Это не принципиально

2018-11-26 19:56 UTC, korzio commented on node/lesson1/server.js
> +    res.write('<h1>NodeJs local server banchmark:<h1><br>\n');
`benchmark`

2018-11-26 19:56 UTC, korzio commented on node/lesson1/request.js
> +const http = require('http');
Хорошо, что использовали встроенный модуль для запросов

2018-11-26 19:56 UTC, korzio commented on node/lesson1/request.js
> +    if (n !== Math.floor(n)) {
В `JavaScript` нельзя узнать, является ли число `integer` или нет :)

2018-11-26 19:56 UTC, korzio commented on node/lesson1/request.js
> +  validate(n, requestType) {
👍

2018-11-26 19:56 UTC, korzio commented on node/lesson1/server.js
> +server.listen(port, hostname, () => {
При запуске программы выводится ошибка

```
node server.js    
Server running at http://127.0.0.1:3000/
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

2018-11-26 19:56 UTC, korzio commented on node/lesson1/server.js
> +  return req.on('end', (error) => {
При запуске `request` - `new request.requester(1000, 'parallel').make().send()` получается ошибка

```
Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

2018-11-26 20:00 UTC, korzio commented on node/lesson1/request.js
> +    } else {
Как вариант, можно использовать что-то похожее на `promiseReduce` из предыдущего задания

2018-11-26 21:30 UTC, dandgerson commented on node/lesson1/request.js
> +const http = require('http');
честно говоря, как это сделать без него, для меня не совсем очевидно

2018-11-26 21:30 UTC, dandgerson commented on node/lesson1/request.js
> +const http = require('http');
честно говоря, как это сделать без него, для меня не совсем очевидно

2018-11-26 21:30 UTC, dandgerson commented on node/lesson1/request.js
> +const http = require('http');
честно говоря, как это сделать без него, для меня не совсем очевидно

2018-11-26 21:42 UTC, dandgerson commented on node/lesson1/request.js
> +const http = require('http');
честно говоря, для меня не совсем очевидно, как это сделать без него

2018-11-26 21:44 UTC, dandgerson commented on node/lesson1/request.js
> +    if (n !== Math.floor(n)) {
я думаю, что можно, 
```
Number.isInteger(n)
```
так, например

2018-11-26 21:46 UTC, dandgerson commented on node/lesson1/server.js
> +  return req.on('end', (error) => {
Да, я её наблюдал, она мне не очевидна.
я вижу её стек, и без гугления мне не ответить, что он означает. нужно отдельно этим заниматься

2018-11-26 21:48 UTC, dandgerson commented on node/lesson1/server.js
> +      console.log('response starting... ' + responseCount++);
точно, это невнимательность

2018-11-26 21:49 UTC, dandgerson commented on node/lesson1/server.js
> +    res.write('<h1>NodeJs local server banchmark:<h1><br>\n');
typo)

2018-11-26 21:50 UTC, dandgerson commented on node/lesson1/server.js
> +new request.requester(1000, 'parallel').make().send();
пока не очевидно, каким образом передать эту строку через npm script.

2018-11-26 21:53 UTC, dandgerson commented on node/lesson1/request.js
> +    } else {
да, у меня была эта идея, но почему- то я от неё отказался, посчитав слишком громоздкой, рассчитыаая на более очевидный вариант. Рассмотрю его снова.

2018-11-26 21:58 UTC, dandgerson commented on node/lesson1/server.js
> +server.listen(port, hostname, () => {
хоть она для меня и не очевидна, подозрения на повторяющийся код с 30 строки, хотя return на 17 должен был прервать дальнейшее выполнение

2018-11-27 09:15 UTC, korzio commented on node/lesson1/request.js
> +const http = require('http');
Можно какой-то внешний, `request` или еще какой. Но здесь не нужно точно

2018-11-27 09:15 UTC, korzio commented on node/lesson1/request.js
> +    if (n !== Math.floor(n)) {
`Number.isInteger(1.0)`
`Number.isInteger(1.000000000000000001)`
ну так

2018-11-27 09:15 UTC, korzio commented on node/lesson1/server.js
> +  return req.on('end', (error) => {
Мне кажется, просто много соединений открывается, но не закрывается

2018-11-27 09:15 UTC, korzio commented on node/lesson1/server.js
> +new request.requester(1000, 'parallel').make().send();
через `process.argv` - стандартно

2018-11-27 16:26 UTC, korzio requested changes

2018-11-27 16:26 UTC, korzio commented on node/lesson1/request.js
> +      let maked = 0;
`made`

2018-11-27 16:26 UTC, korzio commented on node/lesson1/request.js
> +        request.then(result => console.log(++maked + ' request is maked'));
Запросы не дожидаются выполнения

2018-11-27 16:26 UTC, korzio commented on node/lesson1/request.js
> +      this.requests[index] = new Promise((resolve, reject) => {
Конструктуор промиса отработает сразу же после создания, то есть запросы отправятся сразу же

2018-12-03 18:41 UTC, korzio commented
```
lesson1 git:(node-lesson-1) ✗ time node -e "const request = require('./request'); new request.requester(100, 'serial').make().send();"
1 request is made
2 request is made
3 request is made
4 request is made
5 request is made
6 request is made
7 request is made
8 request is made
9 request is made
10 request is made
11 request is made
12 request is made
13 request is made
14 request is made
15 request is made
16 request is made
17 request is made
18 request is made
19 request is made
20 request is made
21 request is made
22 request is made
23 request is made
24 request is made
25 request is made
26 request is made
27 request is made
28 request is made
29 request is made
30 request is made
31 request is made
32 request is made
33 request is made
34 request is made
35 request is made
36 request is made
37 request is made
38 request is made
39 request is made
40 request is made
41 request is made
42 request is made
43 request is made
44 request is made
45 request is made
46 request is made
47 request is made
48 request is made
49 request is made
50 request is made
51 request is made
52 request is made
53 request is made
54 request is made
55 request is made
56 request is made
57 request is made
58 request is made
59 request is made
60 request is made
61 request is made
62 request is made
63 request is made
64 request is made
65 request is made
66 request is made
67 request is made
68 request is made
69 request is made
70 request is made
71 request is made
72 request is made
73 request is made
74 request is made
75 request is made
76 request is made
77 request is made
78 request is made
79 request is made
80 request is made
81 request is made
82 request is made
83 request is made
84 request is made
85 request is made
86 request is made
87 request is made
88 request is made
89 request is made
90 request is made
91 request is made
92 request is made
93 request is made
94 request is made
95 request is made
96 request is made
97 request is made
98 request is made
99 request is made
100 request is made
node -e   0.11s user 0.03s system 58% cpu 0.239 total
➜  lesson1 git:(node-lesson-1) ✗ time node -e "const request = require('./request'); new request.requester(100, 'parallel').make().send();"
node -e   0.11s user 0.03s system 59% cpu 0.228 total
```

Получается, результаты по времени идентичные - значит, где-то ошибка, скорее всего

2018-12-03 18:47 UTC, korzio requested changes

2018-12-03 18:47 UTC, korzio commented on node/lesson1/request.js
> +        requestFunction().then(() => {
Здесь не происходит ожидания завершения предыдущего запроса перед отправкой следующего

2018-12-03 18:47 UTC, korzio commented on node/lesson1/request.js
> +       * вроде бы промисов, и вроде бы он передаётся в нужный метод, Но в
А в какой метод они передаются? `Promise.all()`?

2018-12-03 18:47 UTC, korzio commented on node/lesson1/request.js
> +       * процессе map всё равно ведь происходит последовательный, вызов
В данном случае под параллельными запросами я имел ввиду параллельные именно в этом смысле - отправка происходит сразу всех запросов (хотя технически в коде это выглядит последовательно)

2018-12-03 18:47 UTC, korzio commented on node/lesson1/request.js
> +          resolve(http.get('http://127.0.0.1:3000/'));
Для последовательной отправки запросов я предлагаю добавить `callback` внутрь `http.get()`, и уже тогда делать `resolve()`. Так мы получим цепочку запрос - ответ - следующий запрос

2018-12-03 21:44 UTC, dandgerson commented on node/lesson1/request.js
> +       * вроде бы промисов, и вроде бы он передаётся в нужный метод, Но в
да, я этот метод имел ввиду.

2018-12-04 12:43 UTC, korzio requested changes

2018-12-04 12:43 UTC, korzio commented on node/lesson1/request.js
> +      index++;
Можно делать `this.asyncRequestFunctions.push()` и не париться с `index`

2018-12-04 12:43 UTC, korzio commented on node/lesson1/request.js
> +    const len = this.asyncRequestFunctions.length;
эта строка не выполняется, когда `serialRequester` вызывается, поэтому приложение падает с ошибкой

2018-12-04 16:12 UTC, merged